
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  PrismaClientKnownRequestError,
  PrismaClientUnknownRequestError,
  PrismaClientRustPanicError,
  PrismaClientInitializationError,
  PrismaClientValidationError,
  getPrismaClient,
  sqltag,
  empty,
  join,
  raw,
  skip,
  Decimal,
  Debug,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Extensions,
  warnOnce,
  defineDmmfProperty,
  Public,
  getRuntime,
  createParam,
} = require('./runtime/wasm-compiler-edge.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
Prisma.prismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError;
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError
Prisma.PrismaClientInitializationError = PrismaClientInitializationError
Prisma.PrismaClientValidationError = PrismaClientValidationError
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag
Prisma.empty = empty
Prisma.join = join
Prisma.raw = raw
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = Extensions.getExtensionContext
Prisma.defineExtension = Extensions.defineExtension

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes





/**
 * Enums
 */
exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.GuildSettingScalarFieldEnum = {
  guildId: 'guildId',
  prefix: 'prefix',
  interactionsMode: 'interactionsMode',
  language: 'language',
  errorChannel: 'errorChannel',
  rpEnabled: 'rpEnabled',
  rpEnableRuns: 'rpEnableRuns',
  lastRpSyncRun: 'lastRpSyncRun',
  ptReminderEnabled: 'ptReminderEnabled',
  legacyRp: 'legacyRp',
  editRpCommands: 'editRpCommands',
  enableInvitesAt: 'enableInvitesAt',
  statusChannel: 'statusChannel',
  updatesChannel: 'updatesChannel',
  notifyChannel: 'notifyChannel'
};

exports.Prisma.CustomClientScalarFieldEnum = {
  guildId: 'guildId',
  appId: 'appId',
  token: 'token',
  publicKey: 'publicKey',
  secret: 'secret'
};

exports.Prisma.AfkStateScalarFieldEnum = {
  userId: 'userId',
  reason: 'reason',
  since: 'since',
  guildId: 'guildId'
};

exports.Prisma.AfkSettingScalarFieldEnum = {
  guildId: 'guildId',
  maxLetters: 'maxLetters'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  GuildSetting: 'GuildSetting',
  CustomClient: 'CustomClient',
  AfkState: 'AfkState',
  AfkSetting: 'AfkSetting'
};
/**
 * Create the Client
 */
const config = {
  "previewFeatures": [],
  "clientVersion": "7.2.0",
  "engineVersion": "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3",
  "activeProvider": "postgresql",
  "inlineSchema": "generator client {\n  provider = \"prisma-client-js\"\n  output   = \"../src\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n}\n\n//#region Models\n\nmodel GuildSetting {\n  guildId           String   @db.VarChar\n  prefix            String?\n  interactionsMode  Boolean  @default(true)\n  language          String   @default(\"en-GB\")\n  errorChannel      String?  @db.VarChar\n  rpEnabled         Boolean  @default(false)\n  rpEnableRuns      Decimal  @default(0) @db.Decimal\n  lastRpSyncRun     Decimal? @db.Decimal\n  ptReminderEnabled Boolean  @default(true)\n  legacyRp          Boolean  @default(false)\n  editRpCommands    Boolean  @default(true)\n  enableInvitesAt   Decimal? @db.Decimal\n  statusChannel     String?  @db.VarChar\n  updatesChannel    String?\n  notifyChannel     String?\n\n  @@id([guildId])\n  @@index([guildId])\n}\n\nmodel CustomClient {\n  guildId   String  @db.VarChar\n  appId     String? @db.VarChar\n  token     String? @db.VarChar\n  publicKey String? @db.VarChar\n  secret    String? @db.VarChar\n\n  @@id([guildId])\n  @@index([appId])\n}\n\nmodel AfkState {\n  userId  String  @db.VarChar\n  reason  String?\n  since   Decimal @db.Decimal\n  guildId String  @db.VarChar\n\n  @@id([userId, guildId])\n  @@index([userId, guildId])\n}\n\nmodel AfkSetting {\n  guildId    String @db.VarChar\n  maxLetters Int    @default(250)\n\n  @@id(guildId)\n}\n\n//#endregion\n"
}

config.runtimeDataModel = JSON.parse("{\"models\":{\"GuildSetting\":{\"fields\":[{\"name\":\"guildId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"prefix\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"interactionsMode\",\"kind\":\"scalar\",\"type\":\"Boolean\"},{\"name\":\"language\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"errorChannel\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"rpEnabled\",\"kind\":\"scalar\",\"type\":\"Boolean\"},{\"name\":\"rpEnableRuns\",\"kind\":\"scalar\",\"type\":\"Decimal\"},{\"name\":\"lastRpSyncRun\",\"kind\":\"scalar\",\"type\":\"Decimal\"},{\"name\":\"ptReminderEnabled\",\"kind\":\"scalar\",\"type\":\"Boolean\"},{\"name\":\"legacyRp\",\"kind\":\"scalar\",\"type\":\"Boolean\"},{\"name\":\"editRpCommands\",\"kind\":\"scalar\",\"type\":\"Boolean\"},{\"name\":\"enableInvitesAt\",\"kind\":\"scalar\",\"type\":\"Decimal\"},{\"name\":\"statusChannel\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"updatesChannel\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"notifyChannel\",\"kind\":\"scalar\",\"type\":\"String\"}],\"dbName\":null},\"CustomClient\":{\"fields\":[{\"name\":\"guildId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"appId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"token\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"publicKey\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"secret\",\"kind\":\"scalar\",\"type\":\"String\"}],\"dbName\":null},\"AfkState\":{\"fields\":[{\"name\":\"userId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"reason\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"since\",\"kind\":\"scalar\",\"type\":\"Decimal\"},{\"name\":\"guildId\",\"kind\":\"scalar\",\"type\":\"String\"}],\"dbName\":null},\"AfkSetting\":{\"fields\":[{\"name\":\"guildId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"maxLetters\",\"kind\":\"scalar\",\"type\":\"Int\"}],\"dbName\":null}},\"enums\":{},\"types\":{}}")
defineDmmfProperty(exports.Prisma, config.runtimeDataModel)
config.compilerWasm = {
  getRuntime: async () => require('./query_compiler_bg.js'),
  getQueryCompilerWasmModule: async () => {
    const loader = (await import('#wasm-compiler-loader')).default
    const compiler = (await loader).default
    return compiler
  }
}
if (typeof globalThis !== 'undefined' && globalThis['DEBUG'] || (typeof process !== 'undefined' && process.env && process.env.DEBUG) || undefined) {
  Debug.enable(typeof globalThis !== 'undefined' && globalThis['DEBUG'] || (typeof process !== 'undefined' && process.env && process.env.DEBUG) || undefined)
}

const PrismaClient = getPrismaClient(config)
exports.PrismaClient = PrismaClient
Object.assign(exports, Prisma)
