
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
Prisma.prismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AfkStateScalarFieldEnum = {
  userId: 'userId',
  reason: 'reason',
  since: 'since',
  guildId: 'guildId'
};

exports.Prisma.AfkSettingScalarFieldEnum = {
  guildId: 'guildId',
  maxLetters: 'maxLetters'
};

exports.Prisma.GuildSettingScalarFieldEnum = {
  guildId: 'guildId',
  prefix: 'prefix',
  interactionsMode: 'interactionsMode',
  language: 'language',
  errorChannel: 'errorChannel',
  rpEnabled: 'rpEnabled',
  rpEnableRuns: 'rpEnableRuns',
  lastRpSyncRun: 'lastRpSyncRun',
  ptReminderEnabled: 'ptReminderEnabled',
  legacyRp: 'legacyRp',
  editRpCommands: 'editRpCommands',
  enableInvitesAt: 'enableInvitesAt',
  statusChannel: 'statusChannel',
  updatesChannel: 'updatesChannel',
  notifyChannel: 'notifyChannel'
};

exports.Prisma.AntispamScalarFieldEnum = {
  guildid: 'guildid',
  active: 'active',
  wluserid: 'wluserid',
  wlchannelid: 'wlchannelid',
  wlroleid: 'wlroleid',
  forcedisabled: 'forcedisabled',
  msgthreshold: 'msgthreshold',
  dupemsgthreshold: 'dupemsgthreshold',
  timeout: 'timeout',
  deletespam: 'deletespam',
  action: 'action',
  deletemessageseconds: 'deletemessageseconds',
  duration: 'duration'
};

exports.Prisma.AntivirusScalarFieldEnum = {
  guildid: 'guildid',
  active: 'active',
  linklogging: 'linklogging',
  linklogchannels: 'linklogchannels',
  action: 'action',
  deletemessageseconds: 'deletemessageseconds',
  duration: 'duration',
  deletemsg: 'deletemsg'
};

exports.Prisma.AppealquestionsScalarFieldEnum = {
  guildid: 'guildid',
  uniquetimestamp: 'uniquetimestamp',
  active: 'active',
  question: 'question',
  answertype: 'answertype',
  required: 'required',
  options: 'options'
};

exports.Prisma.AppealsScalarFieldEnum = {
  userid: 'userid',
  guildid: 'guildid',
  punishmentid: 'punishmentid',
  status: 'status',
  received: 'received',
  reason: 'reason'
};

exports.Prisma.AppealanswersScalarFieldEnum = {
  punishmentid: 'punishmentid',
  questionid: 'questionid',
  type: 'type',
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  multiplechoice: 'multiplechoice',
  singlechoice: 'singlechoice'
};

exports.Prisma.AppealsettingsScalarFieldEnum = {
  guildid: 'guildid',
  active: 'active',
  channelid: 'channelid',
  bluserid: 'bluserid',
  reviewroleid: 'reviewroleid'
};

exports.Prisma.ArtScalarFieldEnum = {
  userid: 'userid',
  created: 'created',
  url: 'url',
  verified: 'verified',
  type: 'type',
  desc: 'desc'
};

exports.Prisma.AutopunishScalarFieldEnum = {
  guildid: 'guildid',
  uniquetimestamp: 'uniquetimestamp',
  duration: 'duration',
  warnamount: 'warnamount',
  active: 'active',
  addroles: 'addroles',
  removeroles: 'removeroles',
  deletemessageseconds: 'deletemessageseconds',
  punishment: 'punishment'
};

exports.Prisma.AutorolesScalarFieldEnum = {
  guildid: 'guildid',
  active: 'active',
  botroleid: 'botroleid',
  userroleid: 'userroleid',
  allroleid: 'allroleid'
};

exports.Prisma.BalanceScalarFieldEnum = {
  userid: 'userid',
  guildid: 'guildid',
  balance: 'balance'
};

exports.Prisma.CensorScalarFieldEnum = {
  active: 'active',
  guildid: 'guildid',
  repostroles: 'repostroles',
  repostrules: 'repostrules'
};

exports.Prisma.CustomrolesScalarFieldEnum = {
  guildid: 'guildid',
  userid: 'userid',
  roleid: 'roleid',
  shared: 'shared'
};

exports.Prisma.NewlinesScalarFieldEnum = {
  active: 'active',
  guildid: 'guildid',
  maxnewlines: 'maxnewlines',
  wlroleid: 'wlroleid',
  wlchannelid: 'wlchannelid',
  action: 'action',
  duration: 'duration',
  deletemessageseconds: 'deletemessageseconds'
};

exports.Prisma.InvitesScalarFieldEnum = {
  active: 'active',
  guildid: 'guildid',
  wlroleid: 'wlroleid',
  wlchannelid: 'wlchannelid',
  action: 'action',
  duration: 'duration',
  deletemessageseconds: 'deletemessageseconds'
};

exports.Prisma.ButtonrolesScalarFieldEnum = {
  uniquetimestamp: 'uniquetimestamp',
  roles: 'roles',
  emote: 'emote',
  text: 'text',
  active: 'active',
  guildid: 'guildid',
  linkedid: 'linkedid'
};

exports.Prisma.ButtonrolesettingsScalarFieldEnum = {
  guildid: 'guildid',
  msgid: 'msgid',
  channelid: 'channelid',
  uniquetimestamp: 'uniquetimestamp',
  active: 'active',
  anyroles: 'anyroles',
  onlyone: 'onlyone'
};

exports.Prisma.ContributersScalarFieldEnum = {
  userid: 'userid',
  roles: 'roles'
};

exports.Prisma.CooldownsScalarFieldEnum = {
  command: 'command',
  cooldown: 'cooldown',
  active: 'active',
  wlchannelid: 'wlchannelid',
  wlroleid: 'wlroleid',
  wluserid: 'wluserid',
  activechannelid: 'activechannelid',
  uniquetimestamp: 'uniquetimestamp',
  guildid: 'guildid'
};

exports.Prisma.CustomembedsScalarFieldEnum = {
  color: 'color',
  title: 'title',
  url: 'url',
  authorname: 'authorname',
  authoriconurl: 'authoriconurl',
  authorurl: 'authorurl',
  description: 'description',
  thumbnail: 'thumbnail',
  fieldnames: 'fieldnames',
  fieldvalues: 'fieldvalues',
  fieldinlines: 'fieldinlines',
  image: 'image',
  footertext: 'footertext',
  footericonurl: 'footericonurl',
  uniquetimestamp: 'uniquetimestamp',
  guildid: 'guildid',
  name: 'name',
  timestamp: 'timestamp'
};

exports.Prisma.DisboardScalarFieldEnum = {
  guildid: 'guildid',
  active: 'active',
  nextbump: 'nextbump',
  channelid: 'channelid',
  repeatreminder: 'repeatreminder',
  roles: 'roles',
  users: 'users',
  tempchannelid: 'tempchannelid',
  deletereply: 'deletereply',
  msgid: 'msgid',
  repeatenabled: 'repeatenabled'
};

exports.Prisma.ExpiryScalarFieldEnum = {
  guildid: 'guildid',
  bans: 'bans',
  channelbans: 'channelbans',
  kicks: 'kicks',
  mutes: 'mutes',
  warns: 'warns',
  banstime: 'banstime',
  channelbanstime: 'channelbanstime',
  kickstime: 'kickstime',
  mutestime: 'mutestime',
  warnstime: 'warnstime',
  voice: 'voice',
  voicetime: 'voicetime'
};

exports.Prisma.FilteredWordScalarFieldEnum = {
  keyword: 'keyword',
  filterType: 'filterType'
};

exports.Prisma.GiveawaycollectionScalarFieldEnum = {
  msgid: 'msgid',
  endtime: 'endtime',
  guildid: 'guildid',
  replymsgid: 'replymsgid',
  requiredwinners: 'requiredwinners'
};

exports.Prisma.GiveawaysScalarFieldEnum = {
  guildid: 'guildid',
  msgid: 'msgid',
  description: 'description',
  winnercount: 'winnercount',
  endtime: 'endtime',
  reqrole: 'reqrole',
  actualprize: 'actualprize',
  host: 'host',
  ended: 'ended',
  channelid: 'channelid',
  participants: 'participants',
  collecttime: 'collecttime',
  failreroll: 'failreroll',
  winners: 'winners',
  claimingdone: 'claimingdone'
};

exports.Prisma.GuildsScalarFieldEnum = {
  guildid: 'guildid',
  name: 'name',
  icon: 'icon',
  banner: 'banner',
  invite: 'invite',
  membercount: 'membercount',
  presencecount: 'presencecount',
  fetchat: 'fetchat',
  features: 'features'
};

exports.Prisma.CustomClientScalarFieldEnum = {
  guildId: 'guildId',
  appId: 'appId',
  token: 'token',
  publicKey: 'publicKey',
  secret: 'secret'
};

exports.Prisma.LevelScalarFieldEnum = {
  userid: 'userid',
  guildid: 'guildid',
  type: 'type',
  xp: 'xp',
  multiplier: 'multiplier'
};

exports.Prisma.LevelchannelsScalarFieldEnum = {
  userid: 'userid',
  guildid: 'guildid',
  channelid: 'channelid',
  xp: 'xp'
};

exports.Prisma.LevelingScalarFieldEnum = {
  xppermin: 'xppermin',
  xppermsg: 'xppermsg',
  guildid: 'guildid',
  active: 'active',
  xpmultiplier: 'xpmultiplier',
  rolemode: 'rolemode',
  lvlupdeltimeout: 'lvlupdeltimeout',
  lvlupchannels: 'lvlupchannels',
  lvlupemotes: 'lvlupemotes',
  embed: 'embed',
  ignoreprefixes: 'ignoreprefixes',
  prefixes: 'prefixes',
  minwords: 'minwords',
  lvlupmode: 'lvlupmode',
  blchannelid: 'blchannelid',
  blroleid: 'blroleid',
  bluserid: 'bluserid',
  wlchannelid: 'wlchannelid',
  wlroleid: 'wlroleid',
  wluserid: 'wluserid',
  excludeBots: 'excludeBots',
  minParticipants: 'minParticipants',
  requireUnmute: 'requireUnmute',
  lvluptext: 'lvluptext',
  textenabled: 'textenabled',
  voiceenabled: 'voiceenabled',
  pingUser: 'pingUser',
  cooldown: 'cooldown',
  cooldownType: 'cooldownType',
  msgXpRangeBottom: 'msgXpRangeBottom',
  msgXpRangeTop: 'msgXpRangeTop',
  vcXpRangeBottom: 'vcXpRangeBottom',
  vcXpRangeTop: 'vcXpRangeTop',
  formulaType: 'formulaType',
  curveModifier: 'curveModifier'
};

exports.Prisma.LevelingmultichannelsScalarFieldEnum = {
  guildid: 'guildid',
  channels: 'channels',
  multiplier: 'multiplier',
  uniquetimestamp: 'uniquetimestamp'
};

exports.Prisma.LevelingmultirolesScalarFieldEnum = {
  guildid: 'guildid',
  roles: 'roles',
  multiplier: 'multiplier',
  uniquetimestamp: 'uniquetimestamp'
};

exports.Prisma.LevelingrolesScalarFieldEnum = {
  guildid: 'guildid',
  level: 'level',
  roles: 'roles',
  uniquetimestamp: 'uniquetimestamp'
};

exports.Prisma.LevelingruleschannelsScalarFieldEnum = {
  guildid: 'guildid',
  channels: 'channels',
  uniquetimestamp: 'uniquetimestamp',
  hasleastattachments: 'hasleastattachments',
  hasmostattachments: 'hasmostattachments',
  hasleastcharacters: 'hasleastcharacters',
  hasmostcharacters: 'hasmostcharacters',
  hasleastwords: 'hasleastwords',
  hasmostwords: 'hasmostwords',
  mentionsleastusers: 'mentionsleastusers',
  mentionsmostusers: 'mentionsmostusers',
  mentionsleastchannels: 'mentionsleastchannels',
  mentionsmostchannels: 'mentionsmostchannels',
  mentionsleastroles: 'mentionsleastroles',
  mentionsmostroles: 'mentionsmostroles',
  hasleastlinks: 'hasleastlinks',
  hasmostlinks: 'hasmostlinks',
  hasleastemotes: 'hasleastemotes',
  hasmostemotes: 'hasmostemotes',
  hasleastmentions: 'hasleastmentions',
  hasmostmentions: 'hasmostmentions'
};

exports.Prisma.LogchannelsScalarFieldEnum = {
  guildid: 'guildid',
  applicationevents: 'applicationevents',
  automodevents: 'automodevents',
  channelevents: 'channelevents',
  emojievents: 'emojievents',
  guildevents: 'guildevents',
  scheduledeventevents: 'scheduledeventevents',
  inviteevents: 'inviteevents',
  messageevents: 'messageevents',
  roleevents: 'roleevents',
  stageevents: 'stageevents',
  stickerevents: 'stickerevents',
  typingevents: 'typingevents',
  userevents: 'userevents',
  voiceevents: 'voiceevents',
  webhookevents: 'webhookevents',
  settingslog: 'settingslog',
  modlog: 'modlog',
  memberevents: 'memberevents'
};

exports.Prisma.NitrorolesScalarFieldEnum = {
  guildid: 'guildid',
  uniquetimestamp: 'uniquetimestamp',
  roles: 'roles',
  days: 'days'
};

exports.Prisma.NitrosettingsScalarFieldEnum = {
  guildid: 'guildid',
  active: 'active',
  logchannels: 'logchannels',
  rolemode: 'rolemode',
  notifchannels: 'notifchannels',
  notifembed: 'notifembed',
  notification: 'notification'
};

exports.Prisma.NitrousersScalarFieldEnum = {
  guildid: 'guildid',
  userid: 'userid',
  booststart: 'booststart',
  boostend: 'boostend'
};

exports.Prisma.PunishmentsScalarFieldEnum = {
  guildid: 'guildid',
  userid: 'userid',
  reason: 'reason',
  uniquetimestamp: 'uniquetimestamp',
  channelid: 'channelid',
  channelname: 'channelname',
  executorid: 'executorid',
  executorname: 'executorname',
  msgid: 'msgid',
  duration: 'duration',
  context: 'context',
  type: 'type'
};

exports.Prisma.ReactionrolesScalarFieldEnum = {
  uniquetimestamp: 'uniquetimestamp',
  emote: 'emote',
  roles: 'roles',
  active: 'active',
  guildid: 'guildid',
  linkedid: 'linkedid'
};

exports.Prisma.ReactionrolesettingsScalarFieldEnum = {
  guildid: 'guildid',
  msgid: 'msgid',
  uniquetimestamp: 'uniquetimestamp',
  active: 'active',
  anyroles: 'anyroles',
  channelid: 'channelid'
};

exports.Prisma.ReviewsScalarFieldEnum = {
  userid: 'userid',
  score: 'score',
  content: 'content',
  fetchat: 'fetchat',
  username: 'username',
  avatar: 'avatar'
};

exports.Prisma.RolerewardsScalarFieldEnum = {
  guildid: 'guildid',
  uniquetimestamp: 'uniquetimestamp',
  active: 'active',
  customrole: 'customrole',
  xpmultiplier: 'xpmultiplier',
  currency: 'currency',
  roles: 'roles',
  cansetcolor: 'cansetcolor',
  canseticon: 'canseticon',
  cansetgradient: 'cansetgradient',
  cansetholo: 'cansetholo',
  positionrole: 'positionrole',
  blroleid: 'blroleid',
  bluserid: 'bluserid',
  maxShare: 'maxShare'
};

exports.Prisma.RoleseparatorScalarFieldEnum = {
  guildid: 'guildid',
  separator: 'separator',
  active: 'active',
  stoprole: 'stoprole',
  isvarying: 'isvarying',
  roles: 'roles',
  uniquetimestamp: 'uniquetimestamp'
};

exports.Prisma.RoleseparatorsettingsScalarFieldEnum = {
  guildid: 'guildid',
  stillrunning: 'stillrunning',
  channelid: 'channelid',
  messageid: 'messageid',
  duration: 'duration',
  startat: 'startat',
  index: 'index',
  length: 'length'
};

exports.Prisma.SelfrolesScalarFieldEnum = {
  guildid: 'guildid',
  roles: 'roles',
  onlyone: 'onlyone',
  uniquetimestamp: 'uniquetimestamp',
  active: 'active',
  name: 'name',
  blroleid: 'blroleid',
  bluserid: 'bluserid',
  wlroleid: 'wlroleid',
  wluserid: 'wluserid'
};

exports.Prisma.StatsScalarFieldEnum = {
  userCount: 'userCount',
  guildCount: 'guildCount',
  channelCount: 'channelCount',
  roleCount: 'roleCount',
  allUsers: 'allUsers',
  emoteCount: 'emoteCount',
  stickerCount: 'stickerCount',
  shardCount: 'shardCount',
  clusterCount: 'clusterCount',
  userInstalls: 'userInstalls',
  timestamp: 'timestamp'
};

exports.Prisma.StickyScalarFieldEnum = {
  guildid: 'guildid',
  roles: 'roles',
  stickyrolesmode: 'stickyrolesmode',
  stickyrolesactive: 'stickyrolesactive',
  stickypermsactive: 'stickypermsactive'
};

exports.Prisma.StickymessagesScalarFieldEnum = {
  guildid: 'guildid',
  lastmsgid: 'lastmsgid',
  channelid: 'channelid',
  userid: 'userid'
};

exports.Prisma.StickypermmembersScalarFieldEnum = {
  userid: 'userid',
  guildid: 'guildid',
  channelid: 'channelid',
  denybits: 'denybits',
  allowbits: 'allowbits'
};

exports.Prisma.StickyrolemembersScalarFieldEnum = {
  userid: 'userid',
  guildid: 'guildid',
  roles: 'roles'
};

exports.Prisma.SuggestionsettingsScalarFieldEnum = {
  guildid: 'guildid',
  active: 'active',
  channelid: 'channelid',
  novoteroles: 'novoteroles',
  novoteusers: 'novoteusers',
  approverroleid: 'approverroleid',
  anonvote: 'anonvote',
  nosendroles: 'nosendroles',
  nosendusers: 'nosendusers',
  anonsuggestion: 'anonsuggestion',
  pingroleid: 'pingroleid',
  pinguserid: 'pinguserid',
  deleteapproved: 'deleteapproved',
  deleteapprovedafter: 'deleteapprovedafter',
  deletedenied: 'deletedenied',
  deletedeniedafter: 'deletedeniedafter'
};

exports.Prisma.SuggestionvotesScalarFieldEnum = {
  guildid: 'guildid',
  msgid: 'msgid',
  userid: 'userid',
  downvoted: 'downvoted',
  upvoted: 'upvoted',
  approved: 'approved',
  channelid: 'channelid'
};

exports.Prisma.DmLogScalarFieldEnum = {
  userId: 'userId',
  threadId: 'threadId',
  infoId: 'infoId'
};

exports.Prisma.BlockedusersScalarFieldEnum = {
  userid: 'userid',
  blockeduserid: 'blockeduserid',
  blockedcmd: 'blockedcmd'
};

exports.Prisma.VerificationScalarFieldEnum = {
  guildid: 'guildid',
  logchannel: 'logchannel',
  finishedrole: 'finishedrole',
  pendingrole: 'pendingrole',
  startchannel: 'startchannel',
  selfstart: 'selfstart',
  kickafter: 'kickafter',
  kicktof: 'kicktof',
  active: 'active'
};

exports.Prisma.VoterewardsScalarFieldEnum = {
  guildid: 'guildid',
  uniquetimestamp: 'uniquetimestamp',
  rewardroles: 'rewardroles',
  rewardxpmultiplier: 'rewardxpmultiplier',
  rewardcurrency: 'rewardcurrency',
  rewardxp: 'rewardxp',
  active: 'active',
  linkedid: 'linkedid',
  weekends: 'weekends'
};

exports.Prisma.VotesScalarFieldEnum = {
  guildid: 'guildid',
  userid: 'userid',
  endtime: 'endtime',
  votetype: 'votetype',
  voted: 'voted',
  relatedsetting: 'relatedsetting'
};

exports.Prisma.VotesappliedrewardsScalarFieldEnum = {
  voted: 'voted',
  userid: 'userid',
  rewardroles: 'rewardroles',
  rewardxp: 'rewardxp',
  rewardcurrency: 'rewardcurrency',
  rewardxpmultiplier: 'rewardxpmultiplier',
  relatedvote: 'relatedvote'
};

exports.Prisma.VotesettingsScalarFieldEnum = {
  uniquetimestamp: 'uniquetimestamp',
  guildid: 'guildid',
  token: 'token',
  reminders: 'reminders',
  announcementchannel: 'announcementchannel',
  active: 'active',
  linkedid: 'linkedid',
  name: 'name'
};

exports.Prisma.WelcomeScalarFieldEnum = {
  guildid: 'guildid',
  channelid: 'channelid',
  active: 'active',
  embed: 'embed',
  pingroles: 'pingroles',
  pingusers: 'pingusers',
  pingjoin: 'pingjoin',
  gifChannelId: 'gifChannelId'
};

exports.Prisma.WelcomeGIFScalarFieldEnum = {
  guildId: 'guildId',
  channelId: 'channelId',
  msgId: 'msgId',
  url: 'url'
};

exports.Prisma.DeletethreadsScalarFieldEnum = {
  guildid: 'guildid',
  channelid: 'channelid',
  deletetime: 'deletetime'
};

exports.Prisma.ShopScalarFieldEnum = {
  guildid: 'guildid',
  active: 'active',
  currencyemote: 'currencyemote'
};

exports.Prisma.ShopitemsScalarFieldEnum = {
  guildid: 'guildid',
  roles: 'roles',
  price: 'price',
  uniquetimestamp: 'uniquetimestamp',
  shoptype: 'shoptype',
  buttontext: 'buttontext',
  buttonemote: 'buttonemote',
  msgid: 'msgid',
  channelid: 'channelid',
  active: 'active'
};

exports.Prisma.ShopusersScalarFieldEnum = {
  userid: 'userid',
  guildid: 'guildid',
  boughtids: 'boughtids'
};

exports.Prisma.VoicehubsScalarFieldEnum = {
  guildid: 'guildid',
  channelid: 'channelid',
  active: 'active',
  blroleid: 'blroleid',
  bluserid: 'bluserid',
  categoryid: 'categoryid',
  uniquetimestamp: 'uniquetimestamp',
  wlroleid: 'wlroleid',
  wluserid: 'wluserid',
  deletetime: 'deletetime',
  private: 'private'
};

exports.Prisma.VoicechannelsScalarFieldEnum = {
  ownerid: 'ownerid',
  guildid: 'guildid',
  channelid: 'channelid',
  everyonelefttime: 'everyonelefttime',
  hubid: 'hubid'
};

exports.Prisma.AntiraidScalarFieldEnum = {
  guildid: 'guildid',
  active: 'active',
  posttof: 'posttof',
  pingroles: 'pingroles',
  pingusers: 'pingusers',
  timeout: 'timeout',
  jointhreshold: 'jointhreshold',
  actiontof: 'actiontof',
  action: 'action',
  postchannels: 'postchannels',
  disableinvites: 'disableinvites'
};

exports.Prisma.FeaturesScalarFieldEnum = {
  title: 'title',
  subtitle: 'subtitle',
  image: 'image',
  placeholder: 'placeholder'
};

exports.Prisma.HeartbeatsScalarFieldEnum = {
  ms: 'ms',
  shard: 'shard',
  timestamp: 'timestamp'
};

exports.Prisma.UsersScalarFieldEnum = {
  userid: 'userid',
  username: 'username',
  avatar: 'avatar',
  socials: 'socials',
  socialstype: 'socialstype',
  lastfetch: 'lastfetch',
  ptremindersent: 'ptremindersent',
  votereminders: 'votereminders',
  apiToken: 'apiToken',
  shrtUrlsAccess: 'shrtUrlsAccess',
  displayName: 'displayName'
};

exports.Prisma.TokensScalarFieldEnum = {
  userid: 'userid',
  botid: 'botid',
  accesstoken: 'accesstoken',
  refreshtoken: 'refreshtoken',
  expires: 'expires',
  scopes: 'scopes'
};

exports.Prisma.LinkedRolesDecoScalarFieldEnum = {
  roleId: 'roleId',
  uniquetimestamp: 'uniquetimestamp',
  guildid: 'guildid',
  allowedUsers: 'allowedUsers',
  allowedRoles: 'allowedRoles',
  botId: 'botId',
  botSecret: 'botSecret',
  botToken: 'botToken'
};

exports.Prisma.LinkedRoleTokensScalarFieldEnum = {
  botId: 'botId',
  userId: 'userId',
  token: 'token'
};

exports.Prisma.NoCommandsGuildsScalarFieldEnum = {
  guildId: 'guildId'
};

exports.Prisma.BlockingUsersScalarFieldEnum = {
  userId: 'userId',
  created: 'created'
};

exports.Prisma.UrlScansScalarFieldEnum = {
  url: 'url',
  id: 'id',
  done: 'done',
  expires: 'expires'
};

exports.Prisma.ShrtUrlsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  forward: 'forward'
};

exports.Prisma.ShrtUrlUsesScalarFieldEnum = {
  id: 'id',
  timestamp: 'timestamp'
};

exports.Prisma.VoiceStateUpdateQueueScalarFieldEnum = {
  userId: 'userId',
  guildId: 'guildId',
  deaf: 'deaf',
  mute: 'mute'
};

exports.Prisma.EventScalarFieldEnum = {
  userId: 'userId',
  identId: 'identId',
  hits: 'hits',
  has: 'has'
};

exports.Prisma.PingReportScalarFieldEnum = {
  guildid: 'guildid',
  active: 'active',
  channelIds: 'channelIds',
  cooldown: 'cooldown',
  roleId: 'roleId',
  uniquetimestamp: 'uniquetimestamp'
};

exports.Prisma.VotePunishScalarFieldEnum = {
  guildid: 'guildid',
  active: 'active',
  roleId: 'roleId',
  reqRoleAmount: 'reqRoleAmount',
  uniquetimestamp: 'uniquetimestamp',
  channelIds: 'channelIds',
  cooldown: 'cooldown',
  deleteMessageSeconds: 'deleteMessageSeconds',
  duration: 'duration',
  punishment: 'punishment',
  reqRoles: 'reqRoles',
  blroleid: 'blroleid',
  bluserid: 'bluserid',
  voteInitRoles: 'voteInitRoles'
};

exports.Prisma.ReminderScalarFieldEnum = {
  userId: 'userId',
  channelId: 'channelId',
  reason: 'reason',
  startTime: 'startTime',
  endTime: 'endTime'
};

exports.Prisma.TicketingScalarFieldEnum = {
  uniquetimestamp: 'uniquetimestamp',
  guildid: 'guildid',
  active: 'active',
  logChannelIds: 'logChannelIds',
  archiveCategoryId: 'archiveCategoryId',
  type: 'type',
  archiveDuration: 'archiveDuration',
  channelId: 'channelId',
  categoryId: 'categoryId',
  sendMessagePrefixes: 'sendMessagePrefixes',
  mentionRoles: 'mentionRoles',
  mentionUsers: 'mentionUsers',
  bluserid: 'bluserid',
  blroleid: 'blroleid'
};

exports.Prisma.DMTicketScalarFieldEnum = {
  dmId: 'dmId',
  userId: 'userId',
  channelId: 'channelId',
  settingsId: 'settingsId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.PunishmentType = exports.$Enums.PunishmentType = {
  warn: 'warn',
  kick: 'kick',
  tempmute: 'tempmute',
  ban: 'ban',
  tempban: 'tempban',
  channelban: 'channelban',
  tempchannelban: 'tempchannelban',
  strike: 'strike',
  softban: 'softban'
};

exports.AnswerType = exports.$Enums.AnswerType = {
  paragraph: 'paragraph',
  short: 'short',
  number: 'number',
  boolean: 'boolean',
  multiple_choice: 'multiple_choice',
  single_choice: 'single_choice',
  text: 'text'
};

exports.AppealStatus = exports.$Enums.AppealStatus = {
  pending: 'pending',
  accepted: 'accepted',
  rejected: 'rejected'
};

exports.ArtType = exports.$Enums.ArtType = {
  full: 'full',
  icon: 'icon',
  emoji: 'emoji'
};

exports.AutoPunishPunishmentType = exports.$Enums.AutoPunishPunishmentType = {
  warn: 'warn',
  kick: 'kick',
  tempmute: 'tempmute',
  ban: 'ban',
  tempban: 'tempban',
  channelban: 'channelban',
  tempchannelban: 'tempchannelban',
  softban: 'softban'
};

exports.LevelType = exports.$Enums.LevelType = {
  guild: 'guild',
  global: 'global'
};

exports.LevelUpMode = exports.$Enums.LevelUpMode = {
  messages: 'messages',
  reactions: 'reactions',
  silent: 'silent'
};

exports.FormulaType = exports.$Enums.FormulaType = {
  logarithmic: 'logarithmic',
  linear: 'linear',
  quadratic: 'quadratic',
  cubic: 'cubic',
  polynomial: 'polynomial',
  exponential: 'exponential'
};

exports.StoredPunishmentTypes = exports.$Enums.StoredPunishmentTypes = {
  warn: 'warn',
  kick: 'kick',
  tempmute: 'tempmute',
  ban: 'ban',
  tempban: 'tempban',
  channelban: 'channelban',
  tempchannelban: 'tempchannelban',
  softban: 'softban',
  vctempmute: 'vctempmute',
  vctempdeaf: 'vctempdeaf',
  vcdeaf: 'vcdeaf',
  vcmute: 'vcmute',
  mute: 'mute'
};

exports.WeekendType = exports.$Enums.WeekendType = {
  onlyOnWeekend: 'onlyOnWeekend',
  onlyOnWeekdays: 'onlyOnWeekdays',
  everyDay: 'everyDay'
};

exports.VoteType = exports.$Enums.VoteType = {
  guild: 'guild',
  bot: 'bot'
};

exports.ShopType = exports.$Enums.ShopType = {
  command: 'command',
  message: 'message'
};

exports.AntiRaidPunishmentType = exports.$Enums.AntiRaidPunishmentType = {
  kick: 'kick',
  ban: 'ban'
};

exports.TicketType = exports.$Enums.TicketType = {
  dmToThread: 'dmToThread',
  dmToChannel: 'dmToChannel',
  Thread: 'Thread',
  Channel: 'Channel'
};

exports.Prisma.ModelName = {
  AfkState: 'AfkState',
  AfkSetting: 'AfkSetting',
  GuildSetting: 'GuildSetting',
  antispam: 'antispam',
  antivirus: 'antivirus',
  appealquestions: 'appealquestions',
  appeals: 'appeals',
  appealanswers: 'appealanswers',
  appealsettings: 'appealsettings',
  art: 'art',
  autopunish: 'autopunish',
  autoroles: 'autoroles',
  balance: 'balance',
  censor: 'censor',
  customroles: 'customroles',
  newlines: 'newlines',
  invites: 'invites',
  buttonroles: 'buttonroles',
  buttonrolesettings: 'buttonrolesettings',
  contributers: 'contributers',
  cooldowns: 'cooldowns',
  customembeds: 'customembeds',
  disboard: 'disboard',
  expiry: 'expiry',
  FilteredWord: 'FilteredWord',
  giveawaycollection: 'giveawaycollection',
  giveaways: 'giveaways',
  guilds: 'guilds',
  CustomClient: 'CustomClient',
  level: 'level',
  levelchannels: 'levelchannels',
  leveling: 'leveling',
  levelingmultichannels: 'levelingmultichannels',
  levelingmultiroles: 'levelingmultiroles',
  levelingroles: 'levelingroles',
  levelingruleschannels: 'levelingruleschannels',
  logchannels: 'logchannels',
  nitroroles: 'nitroroles',
  nitrosettings: 'nitrosettings',
  nitrousers: 'nitrousers',
  punishments: 'punishments',
  reactionroles: 'reactionroles',
  reactionrolesettings: 'reactionrolesettings',
  reviews: 'reviews',
  rolerewards: 'rolerewards',
  roleseparator: 'roleseparator',
  roleseparatorsettings: 'roleseparatorsettings',
  selfroles: 'selfroles',
  stats: 'stats',
  sticky: 'sticky',
  stickymessages: 'stickymessages',
  stickypermmembers: 'stickypermmembers',
  stickyrolemembers: 'stickyrolemembers',
  suggestionsettings: 'suggestionsettings',
  suggestionvotes: 'suggestionvotes',
  dmLog: 'dmLog',
  blockedusers: 'blockedusers',
  verification: 'verification',
  voterewards: 'voterewards',
  votes: 'votes',
  votesappliedrewards: 'votesappliedrewards',
  votesettings: 'votesettings',
  welcome: 'welcome',
  WelcomeGIF: 'WelcomeGIF',
  deletethreads: 'deletethreads',
  shop: 'shop',
  shopitems: 'shopitems',
  shopusers: 'shopusers',
  voicehubs: 'voicehubs',
  voicechannels: 'voicechannels',
  antiraid: 'antiraid',
  features: 'features',
  heartbeats: 'heartbeats',
  users: 'users',
  tokens: 'tokens',
  linkedRolesDeco: 'linkedRolesDeco',
  linkedRoleTokens: 'linkedRoleTokens',
  noCommandsGuilds: 'noCommandsGuilds',
  blockingUsers: 'blockingUsers',
  urlScans: 'urlScans',
  shrtUrls: 'shrtUrls',
  shrtUrlUses: 'shrtUrlUses',
  voiceStateUpdateQueue: 'voiceStateUpdateQueue',
  event: 'event',
  pingReport: 'pingReport',
  votePunish: 'votePunish',
  Reminder: 'Reminder',
  ticketing: 'ticketing',
  DMTicket: 'DMTicket'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
