
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
Prisma.prismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.TicketSettingScalarFieldEnum = {
  id: 'id',
  guild: 'guild',
  active: 'active',
  logMode: 'logMode',
  logChannels: 'logChannels',
  createTags: 'createTags',
  claimTags: 'claimTags',
  closeTags: 'closeTags',
  tagClaimer: 'tagClaimer',
  transcriptChannels: 'transcriptChannels',
  archiveCategory: 'archiveCategory',
  archiveDuration: 'archiveDuration',
  type: 'type',
  channel: 'channel',
  category: 'category',
  sendMessagePrefixes: 'sendMessagePrefixes',
  allowCreatorClose: 'allowCreatorClose',
  staffThreads: 'staffThreads',
  staffThreadsChannel: 'staffThreadsChannel',
  mentionRoles: 'mentionRoles',
  mentionUsers: 'mentionUsers',
  staffRoles: 'staffRoles',
  staffUsers: 'staffUsers',
  denyUsers: 'denyUsers',
  denyRoles: 'denyRoles',
  dmEnabled: 'dmEnabled',
  panelChannel: 'panelChannel',
  panelMessage: 'panelMessage',
  panelEmbed: 'panelEmbed',
  panelButtonLabel: 'panelButtonLabel',
  remindUnclaimedAfter: 'remindUnclaimedAfter',
  remindUnclaimedEvery: 'remindUnclaimedEvery',
  remindStaleAfter: 'remindStaleAfter',
  remindStaleEvery: 'remindStaleEvery',
  inactivityWarnAfter: 'inactivityWarnAfter',
  inactivityCloseAfter: 'inactivityCloseAfter',
  remindRoles: 'remindRoles',
  remindUsers: 'remindUsers',
  botToken: 'botToken',
  placementMode: 'placementMode',
  forumChannel: 'forumChannel',
  allowTakeClaim: 'allowTakeClaim',
  staffTierRoles: 'staffTierRoles',
  ticketLimitTotal: 'ticketLimitTotal',
  ticketLimitKind: 'ticketLimitKind'
};

exports.Prisma.TicketScalarFieldEnum = {
  id: 'id',
  dm: 'dm',
  starterDm: 'starterDm',
  user: 'user',
  channel: 'channel',
  settingsId: 'settingsId',
  state: 'state',
  surfaceMessage: 'surfaceMessage',
  claimer: 'claimer',
  claimedAt: 'claimedAt',
  priority: 'priority',
  lastMessageAt: 'lastMessageAt',
  remindAt: 'remindAt',
  tierId: 'tierId'
};

exports.Prisma.TicketPanelScalarFieldEnum = {
  id: 'id',
  guild: 'guild',
  channel: 'channel',
  message: 'message',
  embed: 'embed',
  kinds: 'kinds'
};

exports.Prisma.SnippetsScalarFieldEnum = {
  id: 'id',
  guild: 'guild',
  name: 'name',
  userText: 'userText',
  staffText: 'staffText',
  kinds: 'kinds'
};

exports.Prisma.TicketRoleMapScalarFieldEnum = {
  guild: 'guild',
  roleMapRoles: 'roleMapRoles',
  roleMapLabels: 'roleMapLabels'
};

exports.Prisma.TicketTierScalarFieldEnum = {
  id: 'id',
  settingsId: 'settingsId',
  name: 'name',
  rank: 'rank',
  claimRoles: 'claimRoles',
  category: 'category',
  channel: 'channel',
  reminderSeconds: 'reminderSeconds'
};

exports.Prisma.GuildSettingScalarFieldEnum = {
  guildId: 'guildId',
  prefix: 'prefix',
  interactionsMode: 'interactionsMode',
  language: 'language',
  errorChannel: 'errorChannel',
  rpEnabled: 'rpEnabled',
  rpEnableRuns: 'rpEnableRuns',
  lastRpSyncRun: 'lastRpSyncRun',
  ptReminderEnabled: 'ptReminderEnabled',
  legacyRp: 'legacyRp',
  editRpCommands: 'editRpCommands',
  enableInvitesAt: 'enableInvitesAt',
  statusChannel: 'statusChannel',
  updatesChannel: 'updatesChannel',
  notifyChannel: 'notifyChannel'
};

exports.Prisma.FilteredWordScalarFieldEnum = {
  keyword: 'keyword',
  filterType: 'filterType'
};

exports.Prisma.CustomClientScalarFieldEnum = {
  guildId: 'guildId',
  appId: 'appId',
  token: 'token',
  publicKey: 'publicKey',
  secret: 'secret'
};

exports.Prisma.AfkStateScalarFieldEnum = {
  userId: 'userId',
  reason: 'reason',
  since: 'since',
  guildId: 'guildId'
};

exports.Prisma.AfkSettingScalarFieldEnum = {
  guildId: 'guildId',
  maxLetters: 'maxLetters'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.TicketLogMode = exports.$Enums.TicketLogMode = {
  Channel: 'Channel',
  Thread: 'Thread'
};

exports.TicketType = exports.$Enums.TicketType = {
  dmToThread: 'dmToThread',
  dmToChannel: 'dmToChannel',
  Thread: 'Thread',
  Channel: 'Channel'
};

exports.TicketPlacementMode = exports.$Enums.TicketPlacementMode = {
  SeparateSpaces: 'SeparateSpaces',
  UnifiedForum: 'UnifiedForum'
};

exports.TicketState = exports.$Enums.TicketState = {
  opened: 'opened',
  closed: 'closed',
  claimed: 'claimed',
  prepared: 'prepared',
  deleted: 'deleted'
};

exports.TicketPriority = exports.$Enums.TicketPriority = {
  None: 'None',
  Low: 'Low',
  Medium: 'Medium',
  High: 'High',
  Urgent: 'Urgent'
};

exports.FilterType = exports.$Enums.FilterType = {
  Profanity: 'Profanity',
  SexualContent: 'SexualContent',
  Slurs: 'Slurs'
};

exports.Prisma.ModelName = {
  TicketSetting: 'TicketSetting',
  Ticket: 'Ticket',
  TicketPanel: 'TicketPanel',
  Snippets: 'Snippets',
  TicketRoleMap: 'TicketRoleMap',
  TicketTier: 'TicketTier',
  GuildSetting: 'GuildSetting',
  FilteredWord: 'FilteredWord',
  CustomClient: 'CustomClient',
  AfkState: 'AfkState',
  AfkSetting: 'AfkSetting'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
